name: Release

on:
  push:
    branches:
      - master

jobs:
  create_tag:
    uses: ./.github/workflows/create-tag.yml
    permissions:
      contents: write
  release:
    needs: create_tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.create_tag.outputs.new_tag }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch hatch-vcs

      - name: Generate changelog
        run: python devscripts/make_changelog.py --tag ${{ needs.create_tag.outputs.new_tag }} --package-name krsite-dl

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create_tag.outputs.new_tag }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        run: hatch build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          id-token: ${{ secrets.GITHUB_TOKEN }}
